@startuml

autonumber

Tablero -> Sensor: mostrarTemperaturaReactor(sensor)
activate Tablero
Sensor -> Reactor: getTemperatura()
activate Sensor
activate Reactor
Reactor --> Sensor: Respuesta 300°
deactivate Reactor
Sensor --> Tablero: Respuesta 300°
deactivate Sensor
Tablero -> Console: console.log(temperatura)
deactivate Tablero
activate Console
Consola --> Pantalla: console.log(temperatura)
deactivate Consola


@enduml